### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aprilcs** [the-method/podcast#1]
# Roadmap
### The Method is a peer reviewed, open source podcast about the issues and innovations we care about in science.

Our **important conversations, as scientists, about science,** are:
1. Siloed
2. Evolve sloooooooowly
3. Hierarchical/biased/non inclusive
4. Mostly high level

We **need conversations** that:
1. Include diverse views
2. Are accessible + equitable
3. Improve with every contribution and over time
4. General -> specific

**Podcasting is**:
1. Intimate
2. Non-visual (less implicit bias)
3. Accessible

**Open source**:
1. Allows many people to contribute their little piece of expertise
2. Improves the quality + specificity of the conversation

## Short term - what we're working on now
- [x] Create contributing guidance content for GitHub
- [x] Identify a pilot process for receiving audio contributions
- [ ] Identify a pilot process for receiving text contributions
- [ ] Identify a pilot process for prioritizing contributions
- [ ] Select the topics for the first 3 episodes
- [ ] Conduct interviews for first 3 episodes
- [ ] Conduct peer review for the first 3 episodes
- [x] Create social media accounts
- [x] Circulate a call for contributions
- [ ] Transcribe audio contributions
- [ ] Edit first 3 episodes

## Medium term - what we're doing next
- [ ] Set up podcast hosting
- [ ] Set up RSS feed
- [x] Create social media content + follow friends
- [ ] Release first 3 episodes
- [ ] Update process for receiving audio contributions
- [ ] Update process for receiving text contributions
- [ ] Update process for prioritizing contributions for next release
- [ ] Create "Episodes" page on website

## Long term - what we plan to do 
- [ ] Select the topics for episodes 4-6
- [ ] Conduct interviews for episodes 4-6
- [ ] Conduct peer review for episodes 4-6
- [ ] Update episodes 1-3 with contributions
- [ ] Release new versions of episodes 1-3
- [ ] Release episodes 4-6
- [ ] Organize The Method Hackathon in New York City
- [ ] Set up donation page
